openapi: 3.0.1
info:
  title: OCPS Job Manager API
  description: 'Rubin OCS Controlled Pipeline System (OCPS) Job Management API'
  version: 0.1.0
# servers:
# - url: /api/v1/
#   description: API endpoint base path
tags:
- name: Jobs
  description: Manage jobs
paths:
  /job:
    put:
      tags:
      - Jobs
      summary: Submit a new job
      description: ''
      operationId: newJob
      requestBody:
        description: Job specification
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PutJob'
        required: true
      responses:
        200:
          description: Job submission status and ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PutJobResponse'
  '/job/{job_id}':
    get:
      tags:
      - Jobs
      summary: Request status of an existing job
      operationId: statusJob
      parameters:
      - name: job_id
        in: path
        description: ID of job to return
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetJob'
        '400':
          description: Invalid ID supplied
        '404':
          description: Job not found
components:
  schemas:
    PutJob:
      type: object
      properties:
        type:
          type: string
          description: Job type
          example: "ap"
        env:
          type: object
          description: Environment variables and values required by the job type
          properties:
            AP_FILTER:
              type: string
              description: Example of an environment variable AP_FILTER
              example: g
    PutJobResponse:
      type: object
      properties:
        status:
          type: string
          description: Job creation status
          example: "ok"
        msg:
          type: string
          description: Job creation message
          example: "Job submitted successfully"
        job_id:
          type: string
          description: UUID of new job
          example: "c2c5484c22a8434aa301e4f56d17d595"
    GetJob:
      type: object
      properties:
        status:
          type: string
          description: Job fetch status
          example: "ok"
        msg:
          type: string
          description: Job fetch message
          example: ""
        job:
          type: object
          description: Information about the requested job
          properties:
            clusterId:
              type: string
              description: ID of HTCondor cluster assigned
              example: abc123
            state:
              type: string
              description: State of the job
              example: running
            type:
              type: string
              description: Job type
              example: 'ap'
            input:
              type: object
              description: Input parameter values. Schema depends on job type.
              properties:
                EXAMPLE_PARAM:
                  type: string
                  description: Example of an environment variable EXAMPLE_PARAM
                  example: 'Example of an environment variable EXAMPLE_PARAM'
            output:
              type: object
              description: Job output data
              properties:
                urls:
                  type: array
                  description: URLs to output data files
                  items:
                    type: string
                    description: Output data file URL
                    example: 'https://example.com/path/to/file.dat'
                data:
                  type: object
                  description: Direct output data/information. Schema depends on job type.
                  properties:
                    EXAMPLE:
                      type: string
                      description: Example parameter returned by the job
                      example: 'Example value returned by the job'
