#!/bin/bash

set -e

scriptPath="$(readlink -f "$0")"
scriptDir="$(dirname "${scriptPath}")"
cd "${scriptDir}"

./build_docs
docker run --rm -p 8080:80 -v $PWD/_build/html:/usr/share/nginx/html nginx:1.19.0